### ISSUE TITLE
Publish `master` to `npm`

### ISSUE THREAD

**Issue by twolfson** [najaxjs/najax#15] opened 2015-03-02 23:37 UTC
The `latest` version on `npm` is out of date with what is on `master` by a couple of years. The `latest` is marked as `0.1.5` and currently discards `headers`. It looks like there has been a lot more of activity since then and those updates would be nice to use.

**Comment by doublerebel** [comment] 2015-03-25 01:33
@twolfson Hi, I would be glad to publish the latest version to npm.  @alanclarke Could you please add me as another owner of the npm package (`npm owner add doublerebel najax`)?

Closing as this is a duplicate of #3.

**Closed by doublerebel** 2015-03-25 01:33 UTC
